server:
  port: 8081

logging:
  level:
    root: ERROR
    org:
      springframework:
        web: INFO
        security: INFO
  file: spring.log

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exam?serverTimezone=GMT%2B8&autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456aaa
    driverClassName: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  mvc:
    static-path-pattern: /**
  segment:
    max-file-size: 500
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

sso:
  prefix: http://localhost:8080
  login-page: /user/login
  validate: /validate
  logout: /logout

file:
  save-path: E:/file/

token:
  over-time: 3000



